language: python

sudo: false

env:
  matrix:
    - LUA="lua=5.3"
    - LUA="lua=5.2"
    - LUA="lua=5.1"
    - LUA="luajit=2.1"
    - LUA="luajit=2.0"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PWD/here/bin:$PATH

install:
  - luarocks install ldoc
  - luarocks install ansicolors
  - luarocks install specl
  - luarocks install luacov

script:
  - make
  - luarocks make
  - make check SPECL_OPTS='-vfreport --coverage'

after_success:
  - tail luacov.report.out
  - bash <(curl -s https://codecov.io/bash) -v

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
